version: "3.9"

services:
  db:
    image: postgres:latest
    container_name: codevize_db
    restart: always
    env_file:
      - packages/db/.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  server:
    build:
      context: .
      dockerfile: apps/server/Dockerfile
    container_name: codevize_server
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgres:password@db:5432/codevize
      NODE_ENV: production
    ports:
      - "4000:4000"
    command: bun run start

volumes:
  postgres_data:
